image: ubuntu:latest

stages:
  - gcr-build-client
  

gcr-build-client:
  stage: gcr-build-client
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.gitlab.com
    - docker build -t registry.gitlab.com/sojidaniels/e-commerce/client ./client
    - docker push registry.gitlab.com/sojidaniels/e-commerce/client:latest
    - docker build -t registry.gitlab.com/sojidaniels/e-commerce/purchase ./purchase
    - docker push registry.gitlab.com/sojidaniels/e-commerce/purchase:latest

