image: ubuntu:latest

stages:
  - gcr-build-client
  

gcr-build-client:
  stage: gcr-build-client
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.gitlab.com
    - docker build -t registry.gitlab.com/sojidaniels/e-commerce/client:${CI_COMMIT_SHORT_SHA} ./client
    - docker push registry.gitlab.com/sojidaniels/e-commerce/client:${CI_COMMIT_SHORT_SHA}
    - docker build -t registry.gitlab.com/sojidaniels/e-commerce/purchase:${CI_COMMIT_SHORT_SHA} ./purchase
    - docker push registry.gitlab.com/sojidaniels/e-commerce/purchase:${CI_COMMIT_SHORT_SHA}
    - docker build -t registry.gitlab.com/sojidaniels/e-commerce/catalog:${CI_COMMIT_SHORT_SHA} ./catalog
    - docker push registry.gitlab.com/sojidaniels/e-commerce/catalog:${CI_COMMIT_SHORT_SHA}
    - docker build -t registry.gitlab.com/sojidaniels/e-commerce/carting:${CI_COMMIT_SHORT_SHA} ./carting
    - docker push registry.gitlab.com/sojidaniels/e-commerce/carting:${CI_COMMIT_SHORT_SHA}
    - docker build -t registry.gitlab.com/sojidaniels/e-commerce/wallet:${CI_COMMIT_SHORT_SHA} ./wallet
    - docker push registry.gitlab.com/sojidaniels/e-commerce/wallet:${CI_COMMIT_SHORT_SHA}

