version: '3'
services:
  consul:
    build: ../consul
    network_mode: host
  client: 
    build: ../client
    ports: 
      - "3333:3333"
    network_mode: host
  carting:
    build: ../carting
    ports:
      - "3030:3030"
  catalog:
    build: ../catalog
    ports:
      - "3000:3000"
  purchase:
    build: ../purchase
    ports:
      - "4000:4000"
  wallet:
    build: ../wallet
    ports:
      - "8000:8000"

