version: '3'
services:
  consul:
    build: ../consul
    ports:
      - '8500:8500'
      - '8600:8600/tcp'
      - '8600:8600/udp'
    networks:
      - app_net
  client:
    build: ../client
    ports:
      - "3333:3333"
    depends_on:
      - consul
    networks:
      - app_net
  carting:
    build: ../carting
    ports:
      - "3030:3030"
    depends_on:
      - consul
    networks:
      - app_net
  catalog:
    build: ../catalog
    ports:
      - "3000:3000"
    depends_on:
      - consul
    networks:
      - app_net
  purchase:
    build: ../purchase
    ports:
      - "4000:4000"
    depends_on:
      - consul
    networks:
      - app_net
  wallet:
    build: ../wallet
    ports:
      - "8000:8000"
    depends_on:
      - consul
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
